// Code generated by "stringer -type=QueryErrorKind -trimprefix=QueryErrorKind -output=stringer3.go ."; DO NOT EDIT.

package sitter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QueryErrorNone-0]
	_ = x[QueryErrorSyntax-1]
	_ = x[QueryErrorNodeType-2]
	_ = x[QueryErrorField-3]
	_ = x[QueryErrorCapture-4]
	_ = x[QueryErrorStructure-5]
	_ = x[QueryErrorLanguage-6]
	_ = x[QueryErrorPredicate-100]
}

const (
	_QueryErrorKind_name_0 = "QueryErrorNoneQueryErrorSyntaxQueryErrorNodeTypeQueryErrorFieldQueryErrorCaptureQueryErrorStructureQueryErrorLanguage"
	_QueryErrorKind_name_1 = "QueryErrorPredicate"
)

var _QueryErrorKind_index_0 = [...]uint8{0, 14, 30, 48, 63, 80, 99, 117}

func (i QueryErrorKind) String() string {
	switch {
	case i <= 6:
		return _QueryErrorKind_name_0[_QueryErrorKind_index_0[i]:_QueryErrorKind_index_0[i+1]]
	case i == 100:
		return _QueryErrorKind_name_1
	default:
		return "QueryErrorKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
