// Code generated by "stringer -type=QueryError -trimprefix=QueryError -output=stringer3.go ."; DO NOT EDIT.

package sitter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QueryErrorNone-0]
	_ = x[QueryErrorSyntax-1]
	_ = x[QueryErrorNodeType-2]
	_ = x[QueryErrorField-3]
	_ = x[QueryErrorCapture-4]
	_ = x[QueryErrorStructure-5]
	_ = x[QueryErrorLanguage-6]
}

const _QueryError_name = "NoneSyntaxNodeTypeFieldCaptureStructureLanguage"

var _QueryError_index = [...]uint8{0, 4, 10, 18, 23, 30, 39, 47}

func (i QueryError) String() string {
	if i >= QueryError(len(_QueryError_index)-1) {
		return "QueryError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QueryError_name[_QueryError_index[i]:_QueryError_index[i+1]]
}
