// Code generated by "stringer -type=SymbolType -trimprefix=SymbolType -output=stringer1.go ."; DO NOT EDIT.

package sitter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SymbolTypeRegular-0]
	_ = x[SymbolTypeAnonymous-1]
	_ = x[SymbolTypeAuxiliary-2]
}

const _SymbolType_name = "RegularAnonymousAuxiliary"

var _SymbolType_index = [...]uint8{0, 7, 16, 25}

func (i SymbolType) String() string {
	if i >= SymbolType(len(_SymbolType_index)-1) {
		return "SymbolType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SymbolType_name[_SymbolType_index[i]:_SymbolType_index[i+1]]
}
