// Code generated by "stringer -type=QueryPredicateStepType -trimprefix=QueryPredicateStepType -output=stringer4.go ."; DO NOT EDIT.

package sitter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QueryPredicateStepTypeDone-0]
	_ = x[QueryPredicateStepTypeCapture-1]
	_ = x[QueryPredicateStepTypeString-2]
}

const _QueryPredicateStepType_name = "DoneCaptureString"

var _QueryPredicateStepType_index = [...]uint8{0, 4, 11, 17}

func (i QueryPredicateStepType) String() string {
	if i >= QueryPredicateStepType(len(_QueryPredicateStepType_index)-1) {
		return "QueryPredicateStepType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QueryPredicateStepType_name[_QueryPredicateStepType_index[i]:_QueryPredicateStepType_index[i+1]]
}
